# This is a basic workflow to help you get started with Actions
name: Controlm-Master branch
on:
  push:
    branches: [ "development-controlm" ]
  pull_request:
    branches: [ "development-controlm" ]

jobs:
  call-controlm-master:
    uses: rodrigociro/tsc-init/.github/workflows/control-m.yml@workflows
    with:
      runner: 'ubuntu-latest'
      isRelease: 'true'
    secrets: inherit


