name: GET GITHUB URL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: pre
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $var
        env:
          var: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

